# Generated by Django 4.0.2 on 2022-03-25 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GhanaCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('surname', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('nationality', models.CharField(max_length=50)),
                ('other_names', models.CharField(blank=True, max_length=200, null=True)),
                ('place_of_issuance', models.CharField(max_length=200)),
                ('personal_id_number', models.CharField(max_length=50, unique=True)),
                ('document_number', models.CharField(max_length=50, unique=True)),
                ('sex', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('other', 'other')], max_length=6)),
                ('date_of_issuance', models.DateTimeField(auto_now_add=True)),
                ('date_of_expiry', models.DateTimeField()),
                ('date_of_birth', models.DateField()),
                ('height', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
