# Generated by Django 4.0.2 on 2022-03-25 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pharmacy', '__first__'),
        ('patient', '0001_initial'),
        ('appointment', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('total', models.FloatField()),
                ('insurance_coverage', models.FloatField(blank=True, default=0, null=True)),
                ('status', models.CharField(choices=[('waived', 'waived'), ('pending', 'pending'), ('cancelled', 'cancelled')], default='pending', max_length=15)),
                ('bill_type', models.CharField(choices=[('lump-sum', 'lump-sum'), ('installment', 'installment')], max_length=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('start_time', models.TimeField()),
                ('date', models.DateField()),
                ('appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='visit', to='appointment.appointment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='visits', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='visits', to='patient.patient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('amount', models.FloatField()),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='visit.bill')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='bill',
            name='insurance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='visit.insurance'),
        ),
        migrations.AddField(
            model_name='bill',
            name='visit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='bill', to='visit.visit'),
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField()),
                ('status', models.CharField(choices=[('out-of-stock', 'out-of-stock'), ('outsourced', 'outsourced'), ('pending', 'pending'), ('issued', 'issued')], default='pending', max_length=15)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pharmacy.drug')),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='prescriptions', to=settings.AUTH_USER_MODEL)),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prescription', to='visit.visit')),
            ],
            options={
                'unique_together': {('visit', 'status')},
            },
        ),
    ]
