# Generated by Django 4.0.2 on 2022-03-25 13:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField()),
                ('name', models.CharField(blank=True, max_length=100)),
                ('end_time', models.TimeField()),
                ('start_time', models.TimeField()),
                ('status', models.CharField(choices=[('pending', 'pending'), ('booked', 'booked'), ('confirmed', 'confirmed'), ('cancelled', 'cancelled'), ('rescheduled', 'rescheduled'), ('honoured', 'honoured')], default='pending', max_length=15)),
                ('phone', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='appointements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
